### ISSUE TITLE
[Feature Request] .sublime-local-dependency not only for top sidebar folder

### ISSUE THREAD

**Issue by Kristinita** [spywhere/LocalPackages#1]
### 1. Summary

File `.sublime-local-dependency` was created only for top folder in my sidebar.

### 2. Expected behavior

Create `.sublime-local-dependency` file in folder of open file.

### 3. Actual behavior

`.sublime-local-dependency` file create only in top folder.

### 4. Settings

My sidebar:

![Sidebar](http://i.imgur.com/HLtBCPh.png)

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I want to create `.sublime-local-dependency` file for `CriticMarkup` folder. I open in Sublime Text any file into my `CriticMarkup` folder → <kbd>Ctrl+Shift+P</kbd> → I select desirable packages → <kbd>Enter</kbd> → file `.sublime-local-dependency` create in folder `Киролайна` of my sidebar.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by spywhere** [comment]
Thanks for detailed feature request issue description. However, just to clarify the request, do you want only creating the file or also including apply for specific folder?

**Comment by Kristinita** [comment]
@spywhere, thanks for answer. I want, that add `.sublime-local-dependency` file will be more simply. It would be nice any methods that you consider to be better. Now I need only move desirable folder of my project to top of my sidebar.

**Comment by spywhere** [comment]
Ah, I just catch what you trying to show me there. Would take a few days (hopefully) to get my setup working first though.

**Comment by spywhere** [comment]
This (kind of) bug has been fixed in v0.1.3. Please be patient as it might take up to 6 hours before package control automatically update it for you.

Feel free to give the feedback if this is what you expected or not.

**Comment by Kristinita** [comment]
Now I constantly get messages in console:

```python
[Local Packages] Evaluating missing packages
[Local Packages] Dependencies already installed
```

For example:

```python
[Local Packages] Evaluating missing packages
[Local Packages] Dependencies already installed
key evt: control+`
command: show_panel {"panel": "console", "toggle": true}
key evt: control+p
command: show_overlay {"overlay": "goto", "show_files": true}
chr evt: a (0x61)
[Local Packages] Evaluating missing packages
chr evt: p (0x70)
chr evt: p (0x70)
chr evt: l (0x6c)
chr evt: y (0x79)
[Local Packages] Dependencies already installed
key evt: down
command: move {"by": "lines", "forward": true}
[Local Packages] Evaluating missing packages
```

Could you do so, that I'll saw messages, only if my dependencies not installed? Thanks.

**Comment by spywhere** [comment]
In v0.1.4 (which already pushed) I have stop the logging after first evaluation. However, it will keep evaluating in the background as always.
